# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ThreePointMethod
                                 A QGIS plugin
 Determine the orientation of geological surfaces using three-point vector method.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-08
        copyright            : (C) 2023 by Ewelina Brach
        email                : ewebrach@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ThreePointMethod class from file ThreePointMethod.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ThreePointMethod import ThreePointMethod
    return ThreePointMethod(iface)
